# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=100, verbose_name='\u7ec4\u7ec7\u540d\u79f0')),
                ('org_address', models.CharField(blank=True, max_length=200, verbose_name='\u7ec4\u7ec7\u5730\u5740')),
                ('contract', models.CharField(blank=True, max_length=32, verbose_name='\u8054\u7cfb\u4eba')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='\u6ce8\u518c\u624b\u673a\u53f7')),
                ('access_key_id', models.CharField(blank=True, max_length=64)),
                ('secret_access_key', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(default='cn-north-1', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('role_arn', models.CharField(blank=True, max_length=64)),
                ('bucket', models.CharField(blank=True, max_length=32)),
                ('base', models.CharField(blank=True, max_length=16, verbose_name='prefix')),
                ('options', models.CharField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
